AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    product 2 , refactor and faster interaction wilth villa master product
    
Globals:
  Function:
    Timeout: 10
    CodeUri: ./app
    Runtime: python3.8
    Layers:
      - !Ref LambdaLayer
    VpcConfig:
      SecurityGroupIds:
      - sg-73dae500
      SubnetIds:
      - subnet-0ca9ad2cd96fccccc
    Environment:
      Variables:
        DAX_ENDPOINT: 'longtermcluster.vuu7lr.clustercfg.dax.apse1.cache.amazonaws.com:8111'
        DATABASE_TABLE_NAME: !Join ['-', [ "product-table" , !Ref BRANCH ]]
        REGION: !Ref REGION
        BRANCH: !Ref BRANCH
        SCHEMAURL: ''
      
      
Parameters: 
  BRANCH: 
    Type: String
    Default: dev-manual
    Description: root branch name
  REGION:
    Type: String
    Default: 'ap-southeast-1'
    
    
    
Resources:
  ######## api gateway #######
  Endpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        
  ######## functions ######
  HelloWorld:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "helloworld",!Ref BRANCH ]]
      Handler: app.helloworld
      Policies:
        - arn:aws:iam::394922924679:policy/villaDaxPolicy
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /get
            Method: get
            RestApiId: !Ref Endpoint
            

###### lambdaLayer ######

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdalayer
      ContentUri: ./layer/package.zip
      CompatibleRuntimes:
        - python3.8

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: "*"



Outputs:
  ApiId:
    Value: !Ref Endpoint
  Endpoint:
    Value: !Sub 'https://${Endpoint}.execute-api.${REGION}.amazonaws.com/Prod/'
