# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"helloworld": "helloWorld.ipynb"}

modules = ["helloworld.py"]

doc_url = "https://thanakijwanavit.github.io/src/"

git_url = "https://github.com/thanakijwanavit/src/tree/main/"

def custom_doc_links(name): return None
