# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/helloWorld.ipynb (unless otherwise specified).

__all__ = ['helloworld']

# Cell
from awsSchema.apigateway import Event, Response

# Cell
def helloworld(event, *args):
  print(Event.parseBody(event))
  return Response.returnSuccess()